
import { EffectDef, GlobalParams } from './types';

export const INITIAL_GLOBAL_PARAMS: GlobalParams = {
  hue: 180,
  saturation: 50,
  lightness: 50,
  effectColor: '#40bfbf', // HSL(180, 50, 50)
  gradientPreset: 0,
  bw: false,
  xray: false,
  thermal: false,
  invert: false,
  dramaticWarm: false,
  dramaticCool: false,
  mixMode: false,
  colorMix: false,
  exposure: 0,
  contrast: 1,
  vignette: 0,
  grain: 0,
  chromaticAberration: 0,
  duotone: false,
  applyTo: 'both', 
  maskStrength: 0.5,
  maskThreshold: 0.5,
  autoTracking: false,
  effectEnabled: true,
  effectAmount: 0.85,
  target: 'entire',
  blendMode: 'normal',
  originalMix: 0.25,
  maskFeather: 0.2,
  motionReactivity: 0.5,
  speed: 1,
  previewMode: 'effect',
  stylePreset: 'tech_green',
  animationMode: 'follow_motion',
};

export const GRADIENTS = [
  null,
  { name: 'Cyberpunk', colors: ['#ff00ff', '#00ffff'] },
  { name: 'Sunset', colors: ['#ff5f6d', '#ffc371'] },
  { name: 'Forest', colors: ['#11998e', '#38ef7d'] },
  { name: 'Ocean', colors: ['#2193b0', '#6dd5ed'] },
  { name: 'Royal', colors: ['#6441A5', '#2a0845'] }
];

export const EFFECTS: EffectDef[] = [
  {
    id: 'motion_trail',
    name: 'Motion Trail',
    description: 'Tracked feedback glow that follows moving shapes',
    category: 'video_effect',
    status: 'Complete',
    gpuLoad: 'High',
    defaultParams: {
      trailLength: 0.88,
      decay: 0.38,
      blur: 0.62,
      feedbackScale: 1.035,
      rotation: 0.025,
      glow: 1.25,
      motionReactivity: 0.9,
      effectAmount: 1,
    },
    paramConfig: {
      trailLength: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.65, 1] },
      decay: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.55] },
      blur: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.35, 0.8] },
      feedbackScale: { type: 'slider', min: 0.96, max: 1.08, step: 0.001, randomRange: [1.01, 1.05] },
      rotation: { type: 'slider', min: -0.08, max: 0.08, step: 0.001, randomRange: [-0.04, 0.04] },
      glow: { type: 'slider', min: 0, max: 2, step: 0.01, randomRange: [0.8, 1.6] },
      motionReactivity: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.65, 1] },
      effectAmount: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.75, 1] },
    },
  },
  {
    id: 'rgb_shift',
    name: 'RGB Shift',
    description: 'Shape-aware chromatic separation with stronger tracked edges',
    category: 'video_effect',
    status: 'Complete',
    gpuLoad: 'Medium',
    defaultParams: {
      rgbAmount: 0.04,
      direction: 'radial',
      radialAmount: 0.9,
      jitter: 0.32,
      lensDistortion: 0.45,
      motionReactivity: 0.85,
      edgeOnly: true,
      effectAmount: 1,
    },
    paramConfig: {
      rgbAmount: { type: 'slider', min: 0, max: 0.1, step: 0.001, randomRange: [0.025, 0.06] },
      direction: { type: 'select', options: ['horizontal', 'vertical', 'diagonal', 'radial'] },
      radialAmount: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.55, 1] },
      jitter: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.15, 0.45] },
      lensDistortion: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.25, 0.7] },
      motionReactivity: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.55, 1] },
      edgeOnly: { type: 'toggle' },
      effectAmount: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.75, 1] },
    },
  },
  {
    id: 'neon_edge',
    name: 'Neon Edge',
    description: 'Clear moving-object contour glow with scan accents',
    category: 'video_effect',
    status: 'Complete',
    gpuLoad: 'Medium',
    defaultParams: {
      edgeThickness: 2.6,
      edgeThreshold: 0.14,
      glow: 1.7,
      trail: 0.45,
      growth: 0.55,
      backgroundDim: 0.38,
      motionReactivity: 0.8,
      edgeColor: '#d9ff00',
    },
    paramConfig: {
      edgeThickness: { type: 'slider', min: 0.5, max: 6, step: 0.1, randomRange: [1.8, 4] },
      edgeThreshold: { type: 'slider', min: 0.02, max: 0.8, step: 0.01, randomRange: [0.08, 0.22] },
      glow: { type: 'slider', min: 0, max: 2.5, step: 0.05, randomRange: [1, 2] },
      trail: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.25, 0.7] },
      growth: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.25, 0.75] },
      backgroundDim: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.25, 0.55] },
      motionReactivity: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.55, 1] },
      edgeColor: { type: 'color' },
    },
  },
  {
    id: 'pixel_flow',
    name: 'Pixel Flow',
    description: 'Tracked pseudo pixel sorting and kinetic stretch',
    category: 'video_effect',
    status: 'Complete',
    gpuLoad: 'Medium',
    defaultParams: {
      direction: 'horizontal',
      threshold: 0.34,
      sortLength: 0.62,
      blockSize: 14,
      noise: 0.34,
      speed: 1.6,
      stretchAmount: 0.85,
      motionReactivity: 0.8,
    },
    paramConfig: {
      direction: { type: 'select', options: ['horizontal', 'vertical', 'radial'] },
      threshold: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.5] },
      sortLength: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.35, 0.8] },
      blockSize: { type: 'slider', min: 2, max: 64, step: 1, randomRange: [8, 22] },
      noise: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.15, 0.55] },
      speed: { type: 'slider', min: 0, max: 4, step: 0.1, randomRange: [0.8, 2.4] },
      stretchAmount: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.45, 1] },
      motionReactivity: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.45, 1] },
    },
  },
  {
    id: 'time_scan',
    name: 'Time Scan',
    description: 'Shape-anchored slit-scan wave and scanline trails',
    category: 'video_effect',
    status: 'Complete',
    gpuLoad: 'High',
    defaultParams: {
      timeDepth: 0.8,
      direction: 'horizontal',
      scanWidth: 0.16,
      delay: 0.36,
      repeat: 4,
      wave: 0.7,
      maskFeather: 0.28,
      timeOffset: 0.22,
    },
    paramConfig: {
      timeDepth: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.5, 1] },
      direction: { type: 'select', options: ['horizontal', 'vertical', 'radial'] },
      scanWidth: { type: 'slider', min: 0.02, max: 0.6, step: 0.01, randomRange: [0.08, 0.3] },
      delay: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.18, 0.55] },
      repeat: { type: 'slider', min: 1, max: 8, step: 1, randomRange: [2, 5] },
      wave: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.35, 0.9] },
      maskFeather: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.1, 0.4] },
      timeOffset: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.08, 0.35] },
    },
  },
  {
    id: 'kinetic_plexus',
    name: 'Plexus',
    description: 'Tracked points and restrained connection lines over the subject',
    category: 'kinetic_graphic',
    status: 'Complete',
    gpuLoad: 'Medium',
    defaultParams: {
      pointCount: 120,
      pointSize: 3,
      connectionDistance: 0.12,
      maxConnections: 4,
      lineOpacity: 0.58,
      jitter: 0.02,
      trackingSmoothness: 0.82,
      motionReaction: 0.72,
      glow: 0.26,
    },
    paramConfig: {
      pointCount: { type: 'slider', min: 40, max: 260, step: 5, randomRange: [90, 170] },
      pointSize: { type: 'slider', min: 1, max: 8, step: 0.1, randomRange: [2, 4] },
      connectionDistance: { type: 'slider', min: 0.04, max: 0.25, step: 0.01, randomRange: [0.08, 0.16] },
      maxConnections: { type: 'slider', min: 1, max: 8, step: 1, randomRange: [3, 5] },
      lineOpacity: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.35, 0.8] },
      jitter: { type: 'slider', min: 0, max: 0.08, step: 0.001, randomRange: [0.01, 0.04] },
      trackingSmoothness: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.65, 0.9] },
      motionReaction: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.45, 0.85] },
      glow: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.1, 0.4] },
    },
  },
  {
    id: 'landmark_constellation',
    name: 'Landmark',
    description: 'Constellation-like tracked joints and topology lines',
    category: 'kinetic_graphic',
    status: 'Complete',
    gpuLoad: 'Low',
    defaultParams: {
      landmarkType: 'mixed',
      pointSize: 3,
      lineWidth: 1,
      connectionOpacity: 0.72,
      trackingSmoothness: 0.86,
      pulseAmount: 0.36,
      motionReaction: 0.7,
      trailLength: 0.22,
    },
    paramConfig: {
      landmarkType: { type: 'select', options: ['face', 'hands', 'pose', 'mixed'] },
      pointSize: { type: 'slider', min: 1, max: 8, step: 0.1, randomRange: [2, 4] },
      lineWidth: { type: 'slider', min: 0.5, max: 5, step: 0.1, randomRange: [0.8, 2] },
      connectionOpacity: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.45, 0.85] },
      trackingSmoothness: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.65, 0.92] },
      pulseAmount: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.15, 0.55] },
      motionReaction: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.45, 0.85] },
      trailLength: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.1, 0.4] },
    },
  },
  {
    id: 'tri_mesh',
    name: 'Tri Mesh',
    description: 'Subject-following triangular wireframe and sampled fills',
    category: 'kinetic_graphic',
    status: 'Complete',
    gpuLoad: 'Medium',
    defaultParams: {
      pointDensity: 75,
      meshMode: 'wireframe',
      lineWidth: 1,
      fillOpacity: 0.14,
      distortion: 0.03,
      colorSource: 'custom',
      edgeGlow: 0.22,
      trackingSmoothness: 0.82,
    },
    paramConfig: {
      pointDensity: { type: 'slider', min: 25, max: 160, step: 5, randomRange: [60, 110] },
      meshMode: { type: 'select', options: ['wireframe', 'filled', 'hybrid'] },
      lineWidth: { type: 'slider', min: 0.5, max: 5, step: 0.1, randomRange: [0.8, 2] },
      fillOpacity: { type: 'slider', min: 0, max: 0.6, step: 0.01, randomRange: [0.08, 0.25] },
      distortion: { type: 'slider', min: 0, max: 0.12, step: 0.001, randomRange: [0.01, 0.05] },
      colorSource: { type: 'select', options: ['custom', 'source'] },
      edgeGlow: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.1, 0.35] },
      trackingSmoothness: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.65, 0.9] },
    },
  },
  {
    id: 'edge_trace',
    name: 'Edge Trace',
    description: 'Contour-following scan light and progressive outline',
    category: 'kinetic_graphic',
    status: 'Complete',
    gpuLoad: 'Medium',
    defaultParams: {
      threshold: 0.34,
      lineThickness: 2,
      traceSpeed: 0.8,
      visibleLength: 0.42,
      glow: 0.42,
      trail: 0.28,
      contourSmoothing: 0.76,
      internalEdges: false,
    },
    paramConfig: {
      threshold: { type: 'slider', min: 0.02, max: 0.9, step: 0.01, randomRange: [0.2, 0.5] },
      lineThickness: { type: 'slider', min: 0.5, max: 6, step: 0.1, randomRange: [1.5, 3] },
      traceSpeed: { type: 'slider', min: 0, max: 3, step: 0.1, randomRange: [0.4, 1.4] },
      visibleLength: { type: 'slider', min: 0.05, max: 1, step: 0.01, randomRange: [0.25, 0.65] },
      glow: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.6] },
      trail: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.15, 0.45] },
      contourSmoothing: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.55, 0.9] },
      internalEdges: { type: 'toggle' },
    },
  },
  {
    id: 'particle_drift',
    name: 'Particle Drift',
    description: 'Subject-bound particles floating through a noise field',
    category: 'kinetic_graphic',
    status: 'Lite',
    gpuLoad: 'Medium',
    defaultParams: {
      particleCount: 420,
      particleSize: 2.5,
      driftSpeed: 0.35,
      noiseScale: 0.8,
      noiseStrength: 0.42,
      stickiness: 0.74,
      motionReaction: 0.58,
      lifetime: 5,
      fadeIn: 0.4,
      fadeOut: 0.8,
    },
    paramConfig: {
      particleCount: { type: 'slider', min: 100, max: 1200, step: 20, randomRange: [300, 650] },
      particleSize: { type: 'slider', min: 0.5, max: 7, step: 0.1, randomRange: [1.8, 3.6] },
      driftSpeed: { type: 'slider', min: 0, max: 2, step: 0.01, randomRange: [0.2, 0.8] },
      noiseScale: { type: 'slider', min: 0.1, max: 2, step: 0.01, randomRange: [0.5, 1.2] },
      noiseStrength: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.25, 0.65] },
      stickiness: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.55, 0.9] },
      motionReaction: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.35, 0.75] },
      lifetime: { type: 'slider', min: 1, max: 10, step: 0.1, randomRange: [3, 7] },
      fadeIn: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.6] },
      fadeOut: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.5, 0.9] },
    },
  },
  {
    id: 'ribbon_trails',
    name: 'Ribbon Trails',
    description: 'Tracked center ribbons that stretch with motion',
    category: 'kinetic_graphic',
    status: 'Lite',
    gpuLoad: 'Medium',
    defaultParams: {
      trackingSource: 'object',
      trailLength: 45,
      lineWidth: 3,
      smoothing: 0.82,
      motionWidthReaction: 0.7,
      fadeOut: 0.86,
      ribbonTwist: 0.18,
      glow: 0.28,
    },
    paramConfig: {
      trackingSource: { type: 'select', options: ['face', 'hands', 'object', 'center'] },
      trailLength: { type: 'slider', min: 8, max: 100, step: 1, randomRange: [28, 70] },
      lineWidth: { type: 'slider', min: 0.5, max: 9, step: 0.1, randomRange: [2, 5] },
      smoothing: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.65, 0.9] },
      motionWidthReaction: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.45, 0.85] },
      fadeOut: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.65, 0.95] },
      ribbonTwist: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.08, 0.35] },
      glow: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.15, 0.45] },
    },
  },
  {
    id: 'depth_field',
    name: 'Depth Field',
    description: 'Brightness-depth point field with subject parallax fallback',
    category: 'kinetic_graphic',
    status: 'Mock',
    gpuLoad: 'Experimental',
    defaultParams: {
      pointCount: 8000,
      pointSize: 1.5,
      depthStrength: 0.56,
      parallax: 0.16,
      cameraDrift: 0.12,
      nearClip: 0.05,
      farClip: 0.95,
      originalMix: 0.78,
      depthSmoothing: 0.7,
    },
    paramConfig: {
      pointCount: { type: 'slider', min: 1000, max: 12000, step: 250, randomRange: [4000, 9000] },
      pointSize: { type: 'slider', min: 0.5, max: 5, step: 0.1, randomRange: [1, 2.5] },
      depthStrength: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.35, 0.75] },
      parallax: { type: 'slider', min: 0, max: 0.5, step: 0.01, randomRange: [0.08, 0.22] },
      cameraDrift: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.05, 0.2] },
      nearClip: { type: 'slider', min: 0, max: 0.5, step: 0.01, randomRange: [0.02, 0.1] },
      farClip: { type: 'slider', min: 0.5, max: 1, step: 0.01, randomRange: [0.85, 1] },
      originalMix: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.6, 0.9] },
      depthSmoothing: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.55, 0.85] },
    },
  },
];

export const LEGACY_EFFECTS: EffectDef[] = [
  {
    id: 'vortex',
    name: 'VORTEX',
    description: 'Rotating geometric rings reacting to luminance',
    defaultParams: {
      ringCount: 12,
      rotationSpeed: 1,
      shapeSides: 6,
      complexity: 0.5,
      expansion: 1.2
    },
    paramConfig: {
      ringCount: { type: 'slider', min: 3, max: 30, step: 1, randomRange: [8, 20] },
      rotationSpeed: { type: 'slider', min: -5, max: 5, step: 0.1, randomRange: [0.5, 2] },
      shapeSides: { type: 'slider', min: 3, max: 12, step: 1, randomRange: [3, 8] },
      complexity: { type: 'slider', min: 0.1, max: 2, step: 0.1, randomRange: [0.3, 1.2] },
      expansion: { type: 'slider', min: 0.5, max: 3, step: 0.1, randomRange: [1, 2] },
    },
  },
  {
    id: 'kaleido',
    name: 'KALEIDO',
    description: 'Radial geometric symmetry and tiling',
    defaultParams: {
      segments: 8,
      radius: 0.8,
      rotation: 0,
      zoom: 1.5,
      mirror: true
    },
    paramConfig: {
      segments: { type: 'slider', min: 2, max: 24, step: 1, randomRange: [6, 12] },
      radius: { type: 'slider', min: 0.1, max: 2, step: 0.1, randomRange: [0.5, 1.2] },
      rotation: { type: 'slider', min: 0, max: Math.PI * 2, step: 0.05, randomRange: [0, 3.14] },
      zoom: { type: 'slider', min: 0.5, max: 4, step: 0.1, randomRange: [1, 2.5] },
      mirror: { type: 'toggle' },
    },
  },
  {
    id: 'geometry',
    name: 'GEOMETRY',
    description: 'Recursive polygon tessellation and mesh grid',
    defaultParams: {
      gridSize: 25,
      recursive: 2,
      wireframe: false,
      shape: 'triangle',
      displacement: 15
    },
    paramConfig: {
      gridSize: { type: 'slider', min: 10, max: 60, step: 1, randomRange: [15, 35] },
      recursive: { type: 'slider', min: 0, max: 4, step: 1, randomRange: [1, 3] },
      wireframe: { type: 'toggle' },
      shape: { type: 'select', options: ['triangle', 'hexagon', 'rhombus'] },
      displacement: { type: 'slider', min: 0, max: 100, step: 1, randomRange: [10, 40] },
    },
  },
  {
    id: 'line',
    name: 'LINE',
    description: 'Dynamic edge-detected trails',
    defaultParams: {
      shapeType: 'arrow',
      threshold: 62.5,
      dotSize: 7.75,
      dotRandom: 0.5,
    },
    paramConfig: {
      shapeType: { type: 'select', options: ['arrow', 'dot', 'square', 'number', 'alphabet'] },
      threshold: { type: 'slider', min: 5, max: 120, step: 1, randomRange: [20, 70] },
      dotSize: { type: 'slider', min: 0.5, max: 15, step: 0.5, randomRange: [1, 5] },
      dotRandom: { type: 'slider', min: 0, max: 1, step: 0.1, randomRange: [0.1, 0.8] },
    },
  },
  {
    id: 'pixel',
    name: 'PIXEL',
    description: 'Retro pixelation',
    defaultParams: {
      pixelSize: 33,
      sizeVariance: 0.5,
      posterize: 6,
    },
    paramConfig: {
      pixelSize: { type: 'slider', min: 2, max: 64, step: 1, randomRange: [8, 24] },
      sizeVariance: { type: 'slider', min: 0, max: 1, step: 0.05, randomRange: [0, 0.5] },
    },
  },
  {
    id: 'halftone',
    name: 'HALFTONE',
    description: 'Dynamic dot pattern shading',
    defaultParams: {
      dotSize: 21,
      dotSizeRandom: 0.5,
      angle: 45,
    },
    paramConfig: {
      dotSize: { type: 'slider', min: 2, max: 40, step: 1, randomRange: [5, 20] },
      dotSizeRandom: { type: 'slider', min: 0, max: 1, step: 0.05, randomRange: [0.1, 0.5] },
    },
  },
  {
    id: 'plexus',
    name: 'PLEXUS',
    description: 'Vector-style network connectivity with technical guides',
    defaultParams: {
      shapeType: 'square',
      pointCount: 325,
      linkDistance: 80,
      lineWidth: 2.6,
      pointSize: 5.5,
      pointSizeRandom: 0.5,
      jitter: 10,
      showNumbers: true,
    },
    paramConfig: {
      shapeType: { type: 'select', options: ['arrow', 'dot', 'square', 'number', 'alphabet'] },
      pointCount: { type: 'slider', min: 50, max: 600, step: 10, randomRange: [150, 400] },
      linkDistance: { type: 'slider', min: 10, max: 150, step: 5, randomRange: [40, 90] },
      lineWidth: { type: 'slider', min: 0.2, max: 5, step: 0.1, randomRange: [0.5, 1.5] },
      pointSize: { type: 'slider', min: 1, max: 10, step: 0.5, randomRange: [3, 6] },
      pointSizeRandom: { type: 'slider', min: 0, max: 1, step: 0.05, randomRange: [0.1, 0.5] },
      jitter: { type: 'slider', min: 0, max: 20, step: 0.1, randomRange: [1, 5] },
      showNumbers: { type: 'toggle' },
    },
  },
  {
    id: 'matrix',
    name: 'MATRIX',
    description: 'Global digital rain with trails',
    defaultParams: {
      density: 225,
      fallSpeed: 7.75,
      fontSize: 23,
      language: 'random',
      showNumbers: false,
    },
    paramConfig: {
      density: { type: 'slider', min: 50, max: 400, step: 5, randomRange: [120, 250] },
      fallSpeed: { type: 'slider', min: 0.5, max: 15, step: 0.1, randomRange: [4, 9] },
      fontSize: { type: 'slider', min: 6, max: 40, step: 1, randomRange: [10, 18] },
      language: { type: 'select', options: ['random', 'en', 'jp', 'kr', 'cn', 'ar'] },
      showNumbers: { type: 'toggle' },
    },
  },
  {
    id: 'glitch',
    name: 'GLITCH',
    description: 'Massive Pixel Sorting glitch effect',
    defaultParams: {
      density: 45,
      size: 350,
      thickness: 8,
      threshold: 80,
    },
    paramConfig: {
      density: { type: 'slider', min: 1, max: 150, step: 1, randomRange: [30, 80] },
      size: { type: 'slider', min: 10, max: 800, step: 5, randomRange: [200, 500] },
      thickness: { type: 'slider', min: 1, max: 50, step: 1, randomRange: [4, 15] },
      threshold: { type: 'slider', min: 0, max: 255, step: 1, randomRange: [30, 120] },
    },
  },
  {
    id: 'kinetic_avoid',
    name: 'KINETIC AVOID',
    description: 'Object-aware kinetic blocks that flow around detected video objects',
    defaultParams: {
      density: 42,
      blockScale: 0.68,
      avoidRadius: 0.14,
      repelStrength: 0.85,
      driftSpeed: 1.2,
      colorMode: 'google',
    },
    paramConfig: {
      density: { type: 'slider', min: 16, max: 96, step: 1, randomRange: [32, 64] },
      blockScale: { type: 'slider', min: 0.3, max: 0.95, step: 0.05, randomRange: [0.45, 0.8] },
      avoidRadius: { type: 'slider', min: 0.03, max: 0.35, step: 0.01, randomRange: [0.08, 0.2] },
      repelStrength: { type: 'slider', min: 0, max: 1.8, step: 0.05, randomRange: [0.5, 1.2] },
      driftSpeed: { type: 'slider', min: 0, max: 4, step: 0.1, randomRange: [0.8, 2.4] },
      colorMode: { type: 'select', options: ['google', 'source', 'mono'] },
    },
  },
  {
    id: 'none',
    name: 'ORIGINAL',
    description: 'Clean source without generative effects',
    defaultParams: {},
    paramConfig: {},
  },
];
