
import { EffectDef, GlobalParams } from './types';

export const INITIAL_GLOBAL_PARAMS: GlobalParams = {
  hue: 180,
  saturation: 50,
  lightness: 50,
  effectColor: '#40bfbf', // HSL(180, 50, 50)
  gradientPreset: 0,
  bw: false,
  xray: false,
  thermal: false,
  invert: false,
  dramaticWarm: false,
  dramaticCool: false,
  mixMode: false,
  colorMix: false,
  exposure: 0,
  contrast: 1,
  vignette: 0,
  grain: 0,
  chromaticAberration: 0,
  duotone: false,
  applyTo: 'both', 
  maskStrength: 0.5,
  maskThreshold: 0.5,
  autoTracking: false,
  effectEnabled: true,
  effectAmount: 0.85,
  target: 'entire',
  blendMode: 'normal',
  originalMix: 0.25,
  maskFeather: 0.2,
  motionReactivity: 0.5,
  speed: 1,
  previewMode: 'effect',
};

export const GRADIENTS = [
  null,
  { name: 'Cyberpunk', colors: ['#ff00ff', '#00ffff'] },
  { name: 'Sunset', colors: ['#ff5f6d', '#ffc371'] },
  { name: 'Forest', colors: ['#11998e', '#38ef7d'] },
  { name: 'Ocean', colors: ['#2193b0', '#6dd5ed'] },
  { name: 'Royal', colors: ['#6441A5', '#2a0845'] }
];

export const EFFECTS: EffectDef[] = [
  {
    id: 'motion_trail',
    name: 'Motion Trail',
    description: 'Feedback TOP style motion residue with glow and decay',
    status: 'Complete',
    gpuLoad: 'High',
    reference: {
      label: 'Feedback Effects with Bloom',
      url: 'https://www.youtube.com/watch?v=TLx18b2HFWM',
    },
    defaultParams: {
      trailLength: 0.72,
      decay: 0.62,
      blur: 0.35,
      feedbackScale: 1.018,
      rotation: 0.018,
      glow: 0.7,
      motionReactivity: 0.6,
      effectAmount: 0.9,
    },
    paramConfig: {
      trailLength: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.45, 0.9] },
      decay: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.35, 0.8] },
      blur: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.15, 0.55] },
      feedbackScale: { type: 'slider', min: 0.96, max: 1.08, step: 0.001, randomRange: [0.99, 1.04] },
      rotation: { type: 'slider', min: -0.08, max: 0.08, step: 0.001, randomRange: [-0.03, 0.03] },
      glow: { type: 'slider', min: 0, max: 1.6, step: 0.01, randomRange: [0.3, 1.2] },
      motionReactivity: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.3, 0.9] },
      effectAmount: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.5, 1] },
    },
  },
  {
    id: 'rgb_shift',
    name: 'RGB Shift',
    description: 'Chromatic aberration with radial distortion and jitter',
    status: 'Complete',
    gpuLoad: 'Medium',
    reference: {
      label: 'Chromatic Aberration Effect',
      url: 'https://youtu.be/ZSGdNRkWejM',
    },
    defaultParams: {
      rgbAmount: 0.018,
      direction: 'horizontal',
      radialAmount: 0.45,
      jitter: 0.18,
      lensDistortion: 0.22,
      motionReactivity: 0.5,
      edgeOnly: false,
      effectAmount: 0.85,
    },
    paramConfig: {
      rgbAmount: { type: 'slider', min: 0, max: 0.08, step: 0.001, randomRange: [0.008, 0.035] },
      direction: { type: 'select', options: ['horizontal', 'vertical', 'diagonal', 'radial'] },
      radialAmount: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.8] },
      jitter: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.05, 0.35] },
      lensDistortion: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.05, 0.4] },
      motionReactivity: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.8] },
      edgeOnly: { type: 'toggle' },
      effectAmount: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.5, 1] },
    },
  },
  {
    id: 'neon_edge',
    name: 'Neon Edge',
    description: 'Sobel edge detection with glowing AI-mask-ready outlines',
    status: 'Complete',
    gpuLoad: 'Medium',
    reference: {
      label: 'Edge Feedback Concert Visuals',
      url: 'https://youtu.be/DkZ8dJlO6yg',
    },
    defaultParams: {
      edgeThickness: 1.8,
      edgeThreshold: 0.2,
      glow: 1.1,
      trail: 0.28,
      growth: 0.25,
      backgroundDim: 0.55,
      motionReactivity: 0.35,
      edgeColor: '#40f7ff',
    },
    paramConfig: {
      edgeThickness: { type: 'slider', min: 0.5, max: 6, step: 0.1, randomRange: [1, 3] },
      edgeThreshold: { type: 'slider', min: 0.02, max: 0.8, step: 0.01, randomRange: [0.12, 0.35] },
      glow: { type: 'slider', min: 0, max: 2.5, step: 0.05, randomRange: [0.6, 1.6] },
      trail: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.15, 0.55] },
      growth: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.1, 0.5] },
      backgroundDim: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.35, 0.75] },
      motionReactivity: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.8] },
      edgeColor: { type: 'color' },
    },
  },
  {
    id: 'pixel_flow',
    name: 'Pixel Flow',
    description: 'Pseudo pixel sorting and digital stretch flow',
    status: 'Planned',
    gpuLoad: 'Medium',
    reference: {
      label: 'Pixel Sorting TouchDesigner',
      url: 'https://www.youtube.com/watch?v=xasLIEw23zY',
    },
    defaultParams: {
      direction: 'horizontal',
      threshold: 0.45,
      sortLength: 0.28,
      blockSize: 18,
      noise: 0.22,
      speed: 1,
      stretchAmount: 0.4,
      motionReactivity: 0.4,
    },
    paramConfig: {
      direction: { type: 'select', options: ['horizontal', 'vertical', 'radial'] },
      threshold: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.25, 0.65] },
      sortLength: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.15, 0.55] },
      blockSize: { type: 'slider', min: 2, max: 64, step: 1, randomRange: [8, 28] },
      noise: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.1, 0.45] },
      speed: { type: 'slider', min: 0, max: 4, step: 0.1, randomRange: [0.5, 2] },
      stretchAmount: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.7] },
      motionReactivity: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.8] },
    },
  },
  {
    id: 'time_scan',
    name: 'Time Scan',
    description: 'Slit-scan style temporal displacement interface',
    status: 'Planned',
    gpuLoad: 'High',
    reference: {
      label: 'Slit Scan TouchDesigner',
      url: 'https://www.youtube.com/watch?v=RSeIfK-3zo0',
    },
    defaultParams: {
      timeDepth: 0.55,
      direction: 'horizontal',
      scanWidth: 0.18,
      delay: 0.2,
      repeat: 2,
      wave: 0.35,
      maskFeather: 0.25,
      timeOffset: 0.1,
    },
    paramConfig: {
      timeDepth: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.3, 0.8] },
      direction: { type: 'select', options: ['horizontal', 'vertical', 'radial'] },
      scanWidth: { type: 'slider', min: 0.02, max: 0.6, step: 0.01, randomRange: [0.08, 0.3] },
      delay: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.1, 0.5] },
      repeat: { type: 'slider', min: 1, max: 8, step: 1, randomRange: [1, 4] },
      wave: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.7] },
      maskFeather: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.1, 0.4] },
      timeOffset: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.05, 0.35] },
    },
  },
  {
    id: 'motion_particles',
    name: 'Motion Particles',
    description: 'Frame-difference lite mode particle response',
    status: 'Lite',
    gpuLoad: 'Experimental',
    reference: {
      label: 'Video Motion Controlled Particles',
      url: 'https://youtu.be/Pifp7TTvWEw',
    },
    defaultParams: {
      particleCount: 650,
      particleSize: 2.4,
      motionStrength: 0.65,
      flowSmoothness: 0.42,
      turbulence: 0.35,
      particleLifetime: 0.7,
      motionThreshold: 0.18,
      directionMode: 'follow',
    },
    paramConfig: {
      particleCount: { type: 'slider', min: 100, max: 2000, step: 50, randomRange: [400, 1000] },
      particleSize: { type: 'slider', min: 0.5, max: 8, step: 0.1, randomRange: [1.5, 4] },
      motionStrength: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.3, 0.8] },
      flowSmoothness: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.7] },
      turbulence: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.15, 0.6] },
      particleLifetime: { type: 'slider', min: 0.1, max: 1, step: 0.01, randomRange: [0.4, 0.9] },
      motionThreshold: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.1, 0.35] },
      directionMode: { type: 'select', options: ['follow', 'push', 'pull', 'swirl'] },
    },
  },
  {
    id: 'depth_cloud',
    name: 'Depth Cloud',
    description: 'Brightness-depth mock point cloud controls',
    status: 'Mock',
    gpuLoad: 'Experimental',
    reference: {
      label: 'Point Clouds in TouchDesigner',
      url: 'https://youtu.be/WbnaW3gMmMs',
    },
    defaultParams: {
      depthStrength: 0.55,
      pointSize: 2.6,
      pointDensity: 0.5,
      zScale: 0.6,
      explosion: 0.18,
      noise: 0.25,
      cameraOrbit: 0.35,
      originalMix: 0.35,
    },
    paramConfig: {
      depthStrength: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.3, 0.8] },
      pointSize: { type: 'slider', min: 0.5, max: 8, step: 0.1, randomRange: [1.5, 4] },
      pointDensity: { type: 'slider', min: 0.1, max: 1, step: 0.01, randomRange: [0.35, 0.8] },
      zScale: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.3, 0.8] },
      explosion: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.1, 0.45] },
      noise: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.1, 0.5] },
      cameraOrbit: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.7] },
      originalMix: { type: 'slider', min: 0, max: 1, step: 0.01, randomRange: [0.2, 0.6] },
    },
  },
];

export const LEGACY_EFFECTS: EffectDef[] = [
  {
    id: 'vortex',
    name: 'VORTEX',
    description: 'Rotating geometric rings reacting to luminance',
    defaultParams: {
      ringCount: 12,
      rotationSpeed: 1,
      shapeSides: 6,
      complexity: 0.5,
      expansion: 1.2
    },
    paramConfig: {
      ringCount: { type: 'slider', min: 3, max: 30, step: 1, randomRange: [8, 20] },
      rotationSpeed: { type: 'slider', min: -5, max: 5, step: 0.1, randomRange: [0.5, 2] },
      shapeSides: { type: 'slider', min: 3, max: 12, step: 1, randomRange: [3, 8] },
      complexity: { type: 'slider', min: 0.1, max: 2, step: 0.1, randomRange: [0.3, 1.2] },
      expansion: { type: 'slider', min: 0.5, max: 3, step: 0.1, randomRange: [1, 2] },
    },
  },
  {
    id: 'kaleido',
    name: 'KALEIDO',
    description: 'Radial geometric symmetry and tiling',
    defaultParams: {
      segments: 8,
      radius: 0.8,
      rotation: 0,
      zoom: 1.5,
      mirror: true
    },
    paramConfig: {
      segments: { type: 'slider', min: 2, max: 24, step: 1, randomRange: [6, 12] },
      radius: { type: 'slider', min: 0.1, max: 2, step: 0.1, randomRange: [0.5, 1.2] },
      rotation: { type: 'slider', min: 0, max: Math.PI * 2, step: 0.05, randomRange: [0, 3.14] },
      zoom: { type: 'slider', min: 0.5, max: 4, step: 0.1, randomRange: [1, 2.5] },
      mirror: { type: 'toggle' },
    },
  },
  {
    id: 'geometry',
    name: 'GEOMETRY',
    description: 'Recursive polygon tessellation and mesh grid',
    defaultParams: {
      gridSize: 25,
      recursive: 2,
      wireframe: false,
      shape: 'triangle',
      displacement: 15
    },
    paramConfig: {
      gridSize: { type: 'slider', min: 10, max: 60, step: 1, randomRange: [15, 35] },
      recursive: { type: 'slider', min: 0, max: 4, step: 1, randomRange: [1, 3] },
      wireframe: { type: 'toggle' },
      shape: { type: 'select', options: ['triangle', 'hexagon', 'rhombus'] },
      displacement: { type: 'slider', min: 0, max: 100, step: 1, randomRange: [10, 40] },
    },
  },
  {
    id: 'line',
    name: 'LINE',
    description: 'Dynamic edge-detected trails',
    defaultParams: {
      shapeType: 'arrow',
      threshold: 62.5,
      dotSize: 7.75,
      dotRandom: 0.5,
    },
    paramConfig: {
      shapeType: { type: 'select', options: ['arrow', 'dot', 'square', 'number', 'alphabet'] },
      threshold: { type: 'slider', min: 5, max: 120, step: 1, randomRange: [20, 70] },
      dotSize: { type: 'slider', min: 0.5, max: 15, step: 0.5, randomRange: [1, 5] },
      dotRandom: { type: 'slider', min: 0, max: 1, step: 0.1, randomRange: [0.1, 0.8] },
    },
  },
  {
    id: 'pixel',
    name: 'PIXEL',
    description: 'Retro pixelation',
    defaultParams: {
      pixelSize: 33,
      sizeVariance: 0.5,
      posterize: 6,
    },
    paramConfig: {
      pixelSize: { type: 'slider', min: 2, max: 64, step: 1, randomRange: [8, 24] },
      sizeVariance: { type: 'slider', min: 0, max: 1, step: 0.05, randomRange: [0, 0.5] },
    },
  },
  {
    id: 'halftone',
    name: 'HALFTONE',
    description: 'Dynamic dot pattern shading',
    defaultParams: {
      dotSize: 21,
      dotSizeRandom: 0.5,
      angle: 45,
    },
    paramConfig: {
      dotSize: { type: 'slider', min: 2, max: 40, step: 1, randomRange: [5, 20] },
      dotSizeRandom: { type: 'slider', min: 0, max: 1, step: 0.05, randomRange: [0.1, 0.5] },
    },
  },
  {
    id: 'plexus',
    name: 'PLEXUS',
    description: 'Vector-style network connectivity with technical guides',
    defaultParams: {
      shapeType: 'square',
      pointCount: 325,
      linkDistance: 80,
      lineWidth: 2.6,
      pointSize: 5.5,
      pointSizeRandom: 0.5,
      jitter: 10,
      showNumbers: true,
    },
    paramConfig: {
      shapeType: { type: 'select', options: ['arrow', 'dot', 'square', 'number', 'alphabet'] },
      pointCount: { type: 'slider', min: 50, max: 600, step: 10, randomRange: [150, 400] },
      linkDistance: { type: 'slider', min: 10, max: 150, step: 5, randomRange: [40, 90] },
      lineWidth: { type: 'slider', min: 0.2, max: 5, step: 0.1, randomRange: [0.5, 1.5] },
      pointSize: { type: 'slider', min: 1, max: 10, step: 0.5, randomRange: [3, 6] },
      pointSizeRandom: { type: 'slider', min: 0, max: 1, step: 0.05, randomRange: [0.1, 0.5] },
      jitter: { type: 'slider', min: 0, max: 20, step: 0.1, randomRange: [1, 5] },
      showNumbers: { type: 'toggle' },
    },
  },
  {
    id: 'matrix',
    name: 'MATRIX',
    description: 'Global digital rain with trails',
    defaultParams: {
      density: 225,
      fallSpeed: 7.75,
      fontSize: 23,
      language: 'random',
      showNumbers: false,
    },
    paramConfig: {
      density: { type: 'slider', min: 50, max: 400, step: 5, randomRange: [120, 250] },
      fallSpeed: { type: 'slider', min: 0.5, max: 15, step: 0.1, randomRange: [4, 9] },
      fontSize: { type: 'slider', min: 6, max: 40, step: 1, randomRange: [10, 18] },
      language: { type: 'select', options: ['random', 'en', 'jp', 'kr', 'cn', 'ar'] },
      showNumbers: { type: 'toggle' },
    },
  },
  {
    id: 'glitch',
    name: 'GLITCH',
    description: 'Massive Pixel Sorting glitch effect',
    defaultParams: {
      density: 45,
      size: 350,
      thickness: 8,
      threshold: 80,
    },
    paramConfig: {
      density: { type: 'slider', min: 1, max: 150, step: 1, randomRange: [30, 80] },
      size: { type: 'slider', min: 10, max: 800, step: 5, randomRange: [200, 500] },
      thickness: { type: 'slider', min: 1, max: 50, step: 1, randomRange: [4, 15] },
      threshold: { type: 'slider', min: 0, max: 255, step: 1, randomRange: [30, 120] },
    },
  },
  {
    id: 'kinetic_avoid',
    name: 'KINETIC AVOID',
    description: 'Object-aware kinetic blocks that flow around detected video objects',
    defaultParams: {
      density: 42,
      blockScale: 0.68,
      avoidRadius: 0.14,
      repelStrength: 0.85,
      driftSpeed: 1.2,
      colorMode: 'google',
    },
    paramConfig: {
      density: { type: 'slider', min: 16, max: 96, step: 1, randomRange: [32, 64] },
      blockScale: { type: 'slider', min: 0.3, max: 0.95, step: 0.05, randomRange: [0.45, 0.8] },
      avoidRadius: { type: 'slider', min: 0.03, max: 0.35, step: 0.01, randomRange: [0.08, 0.2] },
      repelStrength: { type: 'slider', min: 0, max: 1.8, step: 0.05, randomRange: [0.5, 1.2] },
      driftSpeed: { type: 'slider', min: 0, max: 4, step: 0.1, randomRange: [0.8, 2.4] },
      colorMode: { type: 'select', options: ['google', 'source', 'mono'] },
    },
  },
  {
    id: 'none',
    name: 'ORIGINAL',
    description: 'Clean source without generative effects',
    defaultParams: {},
    paramConfig: {},
  },
];
